"use client";

import { useEffect, useState, useCallback } from "react";
import LineChart from "@/components/charts/LineChart";
import BarChart from "@/components/charts/BarChart";
import DonutChart from "@/components/charts/DonutChart";
import GaugeChart from "@/components/charts/GaugeChart";
import StackedBarChart from "@/components/charts/StackedBarChart";

// ─── Types ──────────────────────────────────────────────────────────────────

interface KpiData {
  totalDsars: number;
  openDsars: number;
  closedDsars: number;
  avgTimeToCloseDays: number | null;
  medianTimeToCloseDays: number | null;
  extensionRatePct: number | null;
  overdueRatePct: number | null;
  dsarsByType: Record<string, number>;
  dsarsLinkedToIncidentPct: number | null;
  riskDistribution: { green: number; yellow: number; red: number };
  highRiskCasesCount: number;
  incidentLinkedHighRiskCount: number;
  vendorOverdueCount: number;
  autoSuggestedSystemsPct: number | null;
  vendorAutoGeneratedPct: number | null;
  templateResponsePct: number | null;
  idvAutomationPct: number | null;
  apiReadySystemsPct: number | null;
  dpaOnFilePct: number | null;
  systemsCompleteMetaPct: number | null;
  retentionDefinedPct: number | null;
  thirdCountryTransferRatio: number | null;
  estimatedCostPerDsar: number | null;
  estimatedTimeSavedPerDsar: number | null;
  totalTimeSavedMonthly: number | null;
  maturityScore: number | null;
}

interface TrendPoint { date: string; value: number }
interface TrendSeries { metric: string; points: TrendPoint[]; movingAverage: TrendPoint[]; anomalies: TrendPoint[]; changeFromPrevious: number | null; changeFromPreviousPct: number | null }
interface TrendData { series: Record<string, TrendSeries> }

interface ForecastPoint { date: string; predicted: number; lower: number; upper: number }
interface ForecastResult { metric: string; historicalPoints: { date: string; value: number }[]; forecast: ForecastPoint[]; r2: number; modelType: string }
interface ForecastData { dsarVolume: ForecastResult; slBreachProbability: { probability: number; trend: string }; incidentSurgeMultiplier: { multiplier: number } }

interface MaturityDomainScore { domain: string; score: number; details: Record<string, unknown> }

type TabId = "overview" | "risk" | "automation" | "governance" | "forecast" | "reports";

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatMonth(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "short", year: "2-digit" });
}

function KpiCard({ label, value, change, suffix, valueColor }: {
  label: string; value: string | number | null; change?: number | null; suffix?: string; valueColor?: string;
}) {
  return (
    <div className="rounded-lg border border-gray-200 bg-white px-4 py-3">
      <p className="text-xs text-gray-500">{label}</p>
      <p className={`text-2xl font-bold ${valueColor ?? "text-gray-900"}`}>
        {value ?? "—"}{suffix && <span className="text-sm font-normal text-gray-400 ml-0.5">{suffix}</span>}
      </p>
      {change !== undefined && change !== null && (
        <p className={`text-xs mt-0.5 ${change >= 0 ? "text-green-600" : "text-red-600"}`}>
          {change >= 0 ? "+" : ""}{change}% vs prev
        </p>
      )}
    </div>
  );
}

// ─── Main Component ─────────────────────────────────────────────────────────

export default function ExecutiveDashboardPage() {
  const [tab, setTab] = useState<TabId>("overview");
  const [kpi, setKpi] = useState<KpiData | null>(null);
  const [trends, setTrends] = useState<TrendData | null>(null);
  const [forecasts, setForecasts] = useState<ForecastData | null>(null);
  const [maturity, setMaturity] = useState<MaturityDomainScore[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [reportMsg, setReportMsg] = useState("");

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [kpiRes, trendRes, forecastRes, maturityRes] = await Promise.all([
        fetch("/api/executive/kpis"),
        fetch("/api/executive/trends?months=12"),
        fetch("/api/executive/forecasts"),
        fetch("/api/executive/maturity"),
      ]);
      if (kpiRes.ok) setKpi(await kpiRes.json());
      if (trendRes.ok) setTrends(await trendRes.json());
      if (forecastRes.ok) setForecasts(await forecastRes.json());
      if (maturityRes.ok) setMaturity(await maturityRes.json());
    } catch { /* silent */ }
    setLoading(false);
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);

  async function handleGenerateReport(format: string) {
    setGenerating(true);
    setReportMsg("");
    try {
      const res = await fetch("/api/executive/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ format }),
      });
      if (res.ok) {
        const data = await res.json();
        setReportMsg(`Report generated (ID: ${data.reportRunId})`);
      } else {
        const err = await res.json();
        setReportMsg(err.error ?? "Failed to generate report");
      }
    } catch {
      setReportMsg("Network error");
    }
    setGenerating(false);
  }

  async function handleExport(format: string) {
    setGenerating(true);
    setReportMsg("");
    try {
      const res = await fetch("/api/executive/exports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ format, months: 12, includeTrends: true, includeAutomation: true }),
      });
      if (res.ok) {
        setReportMsg(`Export completed successfully`);
      } else {
        const err = await res.json();
        setReportMsg(err.error ?? "Export failed");
      }
    } catch {
      setReportMsg("Network error");
    }
    setGenerating(false);
  }

  const tabs: { id: TabId; label: string }[] = [
    { id: "overview", label: "Overview" },
    { id: "risk", label: "Risk & Compliance" },
    { id: "automation", label: "Automation" },
    { id: "governance", label: "Governance" },
    { id: "forecast", label: "Forecasting" },
    { id: "reports", label: "Reports" },
  ];

  if (loading) {
    return (
      <div className="space-y-6">
        <h1 className="text-xl font-bold text-gray-900">Executive Privacy Dashboard</h1>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          {Array.from({ length: 8 }).map((_, i) => (
            <div key={i} className="card animate-pulse"><div className="h-16 rounded bg-gray-200" /></div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Executive Privacy Dashboard</h1>
          <p className="mt-1 text-sm text-gray-500">
            Strategic KPI overview, trends, and board-ready reporting.
          </p>
        </div>
        <button onClick={fetchData} className="btn-secondary text-sm">Refresh</button>
      </div>

      {/* Tab navigation */}
      <div className="flex gap-1 overflow-x-auto border-b border-gray-200">
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`whitespace-nowrap px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
              tab === t.id
                ? "border-brand-600 text-brand-600"
                : "border-transparent text-gray-500 hover:text-gray-700"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      {tab === "overview" && kpi && <OverviewTab kpi={kpi} trends={trends} />}
      {tab === "risk" && kpi && <RiskTab kpi={kpi} trends={trends} />}
      {tab === "automation" && kpi && <AutomationTab kpi={kpi} trends={trends} />}
      {tab === "governance" && kpi && <GovernanceTab kpi={kpi} maturity={maturity} />}
      {tab === "forecast" && <ForecastTab forecasts={forecasts} />}
      {tab === "reports" && (
        <ReportsTab
          generating={generating}
          reportMsg={reportMsg}
          onGenerateReport={handleGenerateReport}
          onExport={handleExport}
        />
      )}
    </div>
  );
}

// ─── Tab Components ─────────────────────────────────────────────────────────

function OverviewTab({ kpi, trends }: { kpi: KpiData; trends: TrendData | null }) {
  const dsarTrend = trends?.series.totalDsars;
  const closedTrend = trends?.series.closedDsars;

  return (
    <div className="space-y-6">
      {/* KPI cards */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <KpiCard label="Total DSARs" value={kpi.totalDsars} change={dsarTrend?.changeFromPreviousPct} />
        <KpiCard label="Open" value={kpi.openDsars} valueColor={kpi.openDsars > 0 ? "text-blue-600" : undefined} />
        <KpiCard label="Closed" value={kpi.closedDsars} change={closedTrend?.changeFromPreviousPct} />
        <KpiCard label="Avg Close Time" value={kpi.avgTimeToCloseDays} suffix="days" />
      </div>

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <KpiCard label="Overdue Rate" value={kpi.overdueRatePct} suffix="%" valueColor={(kpi.overdueRatePct ?? 0) > 10 ? "text-red-600" : "text-green-600"} />
        <KpiCard label="Extension Rate" value={kpi.extensionRatePct} suffix="%" />
        <KpiCard label="High Risk Cases" value={kpi.highRiskCasesCount} valueColor={kpi.highRiskCasesCount > 0 ? "text-red-600" : undefined} />
        <KpiCard label="Maturity Score" value={kpi.maturityScore} suffix="/100" />
      </div>

      {/* Financial */}
      {kpi.estimatedCostPerDsar !== null && (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
          <KpiCard label="Est. Cost / DSAR" value={`€${kpi.estimatedCostPerDsar}`} />
          <KpiCard label="Time Saved / DSAR" value={kpi.estimatedTimeSavedPerDsar} suffix="min" />
          <KpiCard label="Monthly Time Saved" value={kpi.totalTimeSavedMonthly} suffix="min" />
        </div>
      )}

      {/* DSAR volume trend */}
      {dsarTrend && dsarTrend.points.length > 1 && (
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">DSAR Volume Trend</h3>
          <LineChart
            data={dsarTrend.points.map((p) => ({ label: formatMonth(p.date), value: p.value }))}
            showArea
            color="#6366f1"
          />
        </div>
      )}

      {/* DSARs by type */}
      {Object.keys(kpi.dsarsByType).length > 0 && (
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">DSARs by Type</h3>
          <BarChart
            data={Object.entries(kpi.dsarsByType).map(([label, value]) => ({ label, value }))}
            defaultColor="#8b5cf6"
          />
        </div>
      )}
    </div>
  );
}

function RiskTab({ kpi, trends }: { kpi: KpiData; trends: TrendData | null }) {
  const overdueTrend = trends?.series.overdueRatePct;

  return (
    <div className="space-y-6">
      {/* Risk distribution donut */}
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="card flex flex-col items-center">
          <h3 className="text-sm font-semibold text-gray-900 mb-3 self-start">Risk Distribution</h3>
          <DonutChart
            segments={[
              { label: "Green", value: kpi.riskDistribution.green, color: "#22c55e" },
              { label: "Yellow", value: kpi.riskDistribution.yellow, color: "#eab308" },
              { label: "Red", value: kpi.riskDistribution.red, color: "#ef4444" },
            ]}
            centerValue={String(kpi.riskDistribution.green + kpi.riskDistribution.yellow + kpi.riskDistribution.red)}
            centerLabel="Total"
          />
          <div className="flex gap-4 mt-3 text-xs">
            <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full bg-green-500" />Green: {kpi.riskDistribution.green}</span>
            <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full bg-yellow-500" />Yellow: {kpi.riskDistribution.yellow}</span>
            <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full bg-red-500" />Red: {kpi.riskDistribution.red}</span>
          </div>
        </div>

        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Risk Metrics</h3>
          <div className="space-y-3">
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">High-risk cases</span>
              <span className={`font-semibold ${kpi.highRiskCasesCount > 0 ? "text-red-600" : "text-gray-900"}`}>{kpi.highRiskCasesCount}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Incident-linked high-risk</span>
              <span className="font-semibold text-gray-900">{kpi.incidentLinkedHighRiskCount}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Vendor overdue</span>
              <span className={`font-semibold ${kpi.vendorOverdueCount > 0 ? "text-orange-600" : "text-gray-900"}`}>{kpi.vendorOverdueCount}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Overdue rate</span>
              <span className="font-semibold text-gray-900">{kpi.overdueRatePct ?? "—"}%</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">DSAR-incident link rate</span>
              <span className="font-semibold text-gray-900">{kpi.dsarsLinkedToIncidentPct ?? "—"}%</span>
            </div>
          </div>
        </div>
      </div>

      {/* Overdue trend */}
      {overdueTrend && overdueTrend.points.length > 1 && (
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Overdue Rate Trend</h3>
          <LineChart
            data={overdueTrend.points.map((p) => ({ label: formatMonth(p.date), value: p.value }))}
            color="#ef4444"
            showDots
          />
        </div>
      )}
    </div>
  );
}

function AutomationTab({ kpi, trends }: { kpi: KpiData; trends: TrendData | null }) {
  const metrics = [
    { label: "Auto-Suggested Systems", value: kpi.autoSuggestedSystemsPct, color: "#6366f1" },
    { label: "Template Responses", value: kpi.templateResponsePct, color: "#8b5cf6" },
    { label: "IDV Automation", value: kpi.idvAutomationPct, color: "#a78bfa" },
    { label: "API-Ready Systems", value: kpi.apiReadySystemsPct, color: "#c4b5fd" },
  ];

  const templateTrend = trends?.series.templateResponsePct;

  return (
    <div className="space-y-6">
      {/* Automation gauge cards */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        {metrics.map((m) => (
          <div key={m.label} className="card flex flex-col items-center">
            <GaugeChart value={m.value ?? 0} label={m.label} thresholds={{ green: 50, yellow: 75 }} />
          </div>
        ))}
      </div>

      {/* Stacked bar: automation breakdown by month */}
      {templateTrend && templateTrend.points.length > 1 && (
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Automation Adoption Over Time</h3>
          <StackedBarChart
            data={templateTrend.points.map((p) => ({
              label: formatMonth(p.date),
              segments: [
                { value: p.value, color: "#6366f1", label: "Template %" },
                { value: Math.max(0, 100 - p.value), color: "#e5e7eb", label: "Manual %" },
              ],
            }))}
          />
        </div>
      )}

      {/* Financial impact */}
      {kpi.estimatedCostPerDsar !== null && (
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Efficiency Impact</h3>
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
            <KpiCard label="Time Saved / DSAR" value={kpi.estimatedTimeSavedPerDsar} suffix="min" />
            <KpiCard label="Monthly Time Saved" value={kpi.totalTimeSavedMonthly} suffix="min" />
            <KpiCard label="Est. Cost / DSAR" value={kpi.estimatedCostPerDsar ? `€${kpi.estimatedCostPerDsar}` : null} />
          </div>
        </div>
      )}
    </div>
  );
}

function GovernanceTab({ kpi, maturity }: { kpi: KpiData; maturity: MaturityDomainScore[] | null }) {
  const govMetrics = [
    { label: "DPA Coverage", value: kpi.dpaOnFilePct },
    { label: "System Metadata", value: kpi.systemsCompleteMetaPct },
    { label: "Retention Defined", value: kpi.retentionDefinedPct },
    { label: "3rd Country Transfer", value: kpi.thirdCountryTransferRatio },
  ];

  return (
    <div className="space-y-6">
      {/* Overall maturity gauge */}
      <div className="card flex flex-col items-center py-6">
        <h3 className="text-sm font-semibold text-gray-900 mb-4">Overall Privacy Maturity</h3>
        <GaugeChart value={kpi.maturityScore ?? 0} size={180} thresholds={{ green: 60, yellow: 80 }} />
        <p className="mt-2 text-sm text-gray-500">{kpi.maturityScore ?? 0} / 100</p>
      </div>

      {/* Governance metrics */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        {govMetrics.map((m) => (
          <KpiCard key={m.label} label={m.label} value={m.value} suffix="%" />
        ))}
      </div>

      {/* Maturity by domain */}
      {maturity && maturity.length > 0 && (
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Maturity by Domain</h3>
          <BarChart
            data={maturity.map((m) => ({
              label: m.domain.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
              value: Math.round(m.score),
              color:
                m.score >= 70 ? "#22c55e" :
                m.score >= 40 ? "#eab308" : "#ef4444",
            }))}
            horizontal
          />
        </div>
      )}
    </div>
  );
}

function ForecastTab({ forecasts }: { forecasts: ForecastData | null }) {
  if (!forecasts) {
    return <div className="card text-center py-12 text-sm text-gray-500">No forecast data available. Ensure at least 3 months of KPI snapshots exist.</div>;
  }

  const dsarVol = forecasts.dsarVolume;
  const breach = forecasts.slBreachProbability;
  const surge = forecasts.incidentSurgeMultiplier;

  const historicalData = dsarVol.historicalPoints.map((p) => ({
    label: formatMonth(p.date),
    value: p.value,
  }));

  const forecastData = dsarVol.forecast.map((p) => ({
    label: formatMonth(p.date),
    value: p.predicted,
  }));

  return (
    <div className="space-y-6">
      {/* DSAR volume forecast */}
      <div className="card">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-sm font-semibold text-gray-900">DSAR Volume Forecast</h3>
          <span className="text-xs text-gray-400">R² = {dsarVol.r2} ({dsarVol.modelType})</span>
        </div>
        <LineChart
          data={historicalData}
          forecast={forecastData}
          color="#6366f1"
          forecastColor="#a5b4fc"
          showArea
        />
        <div className="flex items-center gap-4 mt-2 text-xs text-gray-500">
          <span className="flex items-center gap-1"><span className="w-4 h-0.5 bg-indigo-500 inline-block" /> Historical</span>
          <span className="flex items-center gap-1"><span className="w-4 h-0.5 bg-indigo-300 inline-block" style={{ borderTop: "2px dashed" }} /> Forecast</span>
        </div>
      </div>

      {/* Breach probability & surge */}
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
        <div className="card flex flex-col items-center">
          <h3 className="text-sm font-semibold text-gray-900 mb-3 self-start">SLA Breach Probability</h3>
          <GaugeChart
            value={breach.probability}
            label="Next Month"
            size={160}
            thresholds={{ green: 15, yellow: 30 }}
          />
          <p className={`text-xs mt-2 ${
            breach.trend === "improving" ? "text-green-600" :
            breach.trend === "worsening" ? "text-red-600" : "text-gray-500"
          }`}>
            Trend: {breach.trend}
          </p>
        </div>

        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Incident Surge Multiplier</h3>
          <div className="flex items-center justify-center py-8">
            <div className="text-center">
              <p className="text-4xl font-bold text-gray-900">{surge.multiplier}x</p>
              <p className="text-xs text-gray-500 mt-1">DSAR volume multiplier during incidents</p>
            </div>
          </div>
        </div>
      </div>

      {/* Forecast table */}
      <div className="card">
        <h3 className="text-sm font-semibold text-gray-900 mb-3">Forecast Details</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-xs text-gray-500">
                <th className="py-2 pr-4">Month</th>
                <th className="py-2 pr-4">Predicted</th>
                <th className="py-2 pr-4">Lower (80%)</th>
                <th className="py-2">Upper (80%)</th>
              </tr>
            </thead>
            <tbody>
              {dsarVol.forecast.map((f, i) => (
                <tr key={i} className="border-b border-gray-100">
                  <td className="py-2 pr-4 text-gray-700">{formatMonth(f.date)}</td>
                  <td className="py-2 pr-4 font-medium text-gray-900">{f.predicted}</td>
                  <td className="py-2 pr-4 text-gray-500">{f.lower}</td>
                  <td className="py-2 text-gray-500">{f.upper}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function ReportsTab({ generating, reportMsg, onGenerateReport, onExport }: {
  generating: boolean;
  reportMsg: string;
  onGenerateReport: (format: string) => void;
  onExport: (format: string) => void;
}) {
  return (
    <div className="space-y-6">
      {/* Report generation */}
      <div className="card">
        <h3 className="text-sm font-semibold text-gray-900 mb-3">Generate Board Report</h3>
        <p className="text-xs text-gray-500 mb-4">
          Generate a comprehensive board-ready report with all KPI sections, trends, and recommendations.
        </p>
        <div className="flex flex-wrap gap-3">
          <button
            onClick={() => onGenerateReport("JSON")}
            disabled={generating}
            className="btn-primary"
          >
            {generating ? "Generating..." : "Generate JSON Report"}
          </button>
          <button
            onClick={() => onGenerateReport("CSV")}
            disabled={generating}
            className="btn-secondary"
          >
            Generate CSV Report
          </button>
          <button
            onClick={() => onGenerateReport("PPT_JSON")}
            disabled={generating}
            className="btn-secondary"
          >
            Generate PPT-Ready JSON
          </button>
        </div>
      </div>

      {/* Data export */}
      <div className="card">
        <h3 className="text-sm font-semibold text-gray-900 mb-3">Export KPI Data</h3>
        <p className="text-xs text-gray-500 mb-4">
          Export raw KPI snapshot data for external analysis. Includes 12-month history.
        </p>
        <div className="flex flex-wrap gap-3">
          <button
            onClick={() => onExport("CSV")}
            disabled={generating}
            className="btn-secondary"
          >
            Export CSV
          </button>
          <button
            onClick={() => onExport("JSON")}
            disabled={generating}
            className="btn-secondary"
          >
            Export JSON
          </button>
        </div>
      </div>

      {reportMsg && (
        <div className={`rounded-lg px-4 py-3 text-sm ${
          reportMsg.includes("error") || reportMsg.includes("Failed")
            ? "bg-red-50 text-red-700 border border-red-200"
            : "bg-green-50 text-green-700 border border-green-200"
        }`}>
          {reportMsg}
        </div>
      )}
    </div>
  );
}
