export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { checkPermission } from "@/lib/rbac";
import { logAudit, getClientInfo } from "@/lib/audit";
import { ApiError, handleApiError } from "@/lib/errors";
import { getStorage } from "@/lib/storage";
import archiver from "archiver";
import { PassThrough } from "stream";

interface RouteParams {
  params: { id: string };
}

function escapeCSV(value: string | null | undefined): string {
  if (value == null) return "";
  const str = String(value);
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function generateCoverLetterHTML(dsarCase: any, tenantName: string): string {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>DSAR Response - ${dsarCase.caseNumber}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
    h1 { color: #1a365d; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #1e40af; margin-top: 30px; }
    .meta { background: #f0f4ff; padding: 15px; border-radius: 8px; margin: 20px 0; }
    .meta dt { font-weight: bold; color: #555; }
    .meta dd { margin: 0 0 10px 0; }
    table { border-collapse: collapse; width: 100%; margin: 15px 0; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f8fafc; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #666; }
  </style>
</head>
<body>
  <h1>Data Subject Access Request Response</h1>
  <p>Date: ${today}</p>

  <div class="meta">
    <dl>
      <dt>Case Number</dt><dd>${dsarCase.caseNumber}</dd>
      <dt>Request Type</dt><dd>${dsarCase.type}</dd>
      <dt>Status</dt><dd>${dsarCase.status}</dd>
      <dt>Data Subject</dt><dd>${dsarCase.dataSubject?.fullName ?? "N/A"}</dd>
      <dt>Received</dt><dd>${new Date(dsarCase.receivedAt).toLocaleDateString()}</dd>
      <dt>Due Date</dt><dd>${new Date(dsarCase.dueDate).toLocaleDateString()}</dd>
      <dt>Organization</dt><dd>${tenantName}</dd>
    </dl>
  </div>

  <h2>Response Summary</h2>
  <p>${dsarCase.description || "No description provided."}</p>

  <h2>Request Details</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Channel</td><td>${dsarCase.channel || "N/A"}</td></tr>
    <tr><td>Requester Type</td><td>${dsarCase.requesterType || "N/A"}</td></tr>
    <tr><td>Lawful Basis</td><td>${dsarCase.lawfulBasis || "N/A"}</td></tr>
    <tr><td>Identity Verified</td><td>${dsarCase.identityVerified ? "Yes" : "No"}</td></tr>
    <tr><td>Priority</td><td>${dsarCase.priority}</td></tr>
  </table>

  <div class="footer">
    <p>This document was automatically generated by PrivacyPilot DSAR Management Platform.</p>
    <p>Generated on ${today} for case ${dsarCase.caseNumber}.</p>
  </div>
</body>
</html>`;
}

export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const user = await requireAuth();
    checkPermission(user.role, "export", "read");

    const dsarCase = await prisma.dSARCase.findFirst({
      where: {
        id: params.id,
        tenantId: user.tenantId,
      },
      include: {
        dataSubject: true,
        createdBy: { select: { id: true, name: true, email: true } },
        assignedTo: { select: { id: true, name: true, email: true } },
      },
    });

    if (!dsarCase) {
      throw new ApiError(404, "Case not found");
    }

    const tenant = await prisma.tenant.findUnique({
      where: { id: user.tenantId },
      select: { name: true },
    });

    // Fetch all related data in parallel
    const [stateTransitions, tasks, comments, auditLogs, documents, communications, dataCollectionItems, legalReviews] =
      await Promise.all([
        prisma.dSARStateTransition.findMany({
          where: { caseId: params.id, tenantId: user.tenantId },
          include: { changedBy: { select: { id: true, name: true, email: true } } },
          orderBy: { changedAt: "asc" },
        }),
        prisma.task.findMany({
          where: { caseId: params.id, tenantId: user.tenantId },
          include: {
            assignee: { select: { id: true, name: true, email: true } },
            system: { select: { id: true, name: true } },
          },
          orderBy: { createdAt: "asc" },
        }),
        prisma.comment.findMany({
          where: { caseId: params.id, tenantId: user.tenantId },
          include: { author: { select: { id: true, name: true, email: true } } },
          orderBy: { createdAt: "asc" },
        }),
        prisma.auditLog.findMany({
          where: { entityType: "DSARCase", entityId: params.id, tenantId: user.tenantId },
          orderBy: { createdAt: "asc" },
        }),
        prisma.document.findMany({
          where: { caseId: params.id, tenantId: user.tenantId, deletedAt: null },
          include: { uploadedBy: { select: { id: true, name: true, email: true } } },
          orderBy: { uploadedAt: "asc" },
        }),
        prisma.communicationLog.findMany({
          where: { caseId: params.id, tenantId: user.tenantId },
          orderBy: { sentAt: "asc" },
        }),
        prisma.dataCollectionItem.findMany({
          where: { caseId: params.id, tenantId: user.tenantId },
          include: { system: { select: { id: true, name: true } } },
          orderBy: { createdAt: "asc" },
        }),
        prisma.legalReview.findMany({
          where: { caseId: params.id, tenantId: user.tenantId },
          include: { reviewer: { select: { id: true, name: true, email: true } } },
          orderBy: { createdAt: "asc" },
        }),
      ]);

    // Build the ZIP archive
    const archive = archiver("zip", { zlib: { level: 9 } });
    const passthrough = new PassThrough();
    archive.pipe(passthrough);

    // Cover letter HTML
    archive.append(
      generateCoverLetterHTML(dsarCase, tenant?.name ?? "N/A"),
      { name: "cover-letter.html" }
    );

    // JSON data files
    const caseExport = {
      id: dsarCase.id,
      caseNumber: dsarCase.caseNumber,
      type: dsarCase.type,
      status: dsarCase.status,
      priority: dsarCase.priority,
      lawfulBasis: dsarCase.lawfulBasis,
      channel: dsarCase.channel,
      requesterType: dsarCase.requesterType,
      description: dsarCase.description,
      identityVerified: dsarCase.identityVerified,
      receivedAt: dsarCase.receivedAt,
      dueDate: dsarCase.dueDate,
      extendedDueDate: dsarCase.extendedDueDate,
      createdAt: dsarCase.createdAt,
      updatedAt: dsarCase.updatedAt,
      dataSubject: dsarCase.dataSubject,
      createdBy: dsarCase.createdBy,
      assignedTo: dsarCase.assignedTo,
    };

    archive.append(JSON.stringify(caseExport, null, 2), { name: "case.json" });
    archive.append(JSON.stringify(stateTransitions, null, 2), { name: "timeline.json" });
    archive.append(JSON.stringify(tasks, null, 2), { name: "tasks.json" });
    archive.append(JSON.stringify(comments, null, 2), { name: "comments.json" });
    archive.append(JSON.stringify(auditLogs, null, 2), { name: "audit_log.json" });
    archive.append(JSON.stringify(communications, null, 2), { name: "communications.json" });
    archive.append(JSON.stringify(dataCollectionItems, null, 2), { name: "data_collection.json" });
    archive.append(JSON.stringify(legalReviews, null, 2), { name: "legal_reviews.json" });

    // CSV: Case summary
    const caseCSV = [
      "Field,Value",
      `Case Number,${escapeCSV(dsarCase.caseNumber)}`,
      `Type,${escapeCSV(dsarCase.type)}`,
      `Status,${escapeCSV(dsarCase.status)}`,
      `Priority,${escapeCSV(dsarCase.priority)}`,
      `Data Subject,${escapeCSV(dsarCase.dataSubject.fullName)}`,
      `Email,${escapeCSV(dsarCase.dataSubject.email)}`,
      `Received,${escapeCSV(new Date(dsarCase.receivedAt).toISOString())}`,
      `Due Date,${escapeCSV(new Date(dsarCase.dueDate).toISOString())}`,
      `Channel,${escapeCSV(dsarCase.channel)}`,
      `Identity Verified,${dsarCase.identityVerified ? "Yes" : "No"}`,
      `Assignee,${escapeCSV(dsarCase.assignedTo?.name)}`,
    ].join("\n");
    archive.append(caseCSV, { name: "case-summary.csv" });

    // CSV: Tasks
    if (tasks.length > 0) {
      const taskHeaders = "Title,Status,Assignee,Due Date,System,Description";
      const taskRows = tasks.map((t: any) =>
        [
          escapeCSV(t.title),
          escapeCSV(t.status),
          escapeCSV(t.assignee?.name),
          escapeCSV(t.dueDate ? new Date(t.dueDate).toISOString() : ""),
          escapeCSV(t.system?.name),
          escapeCSV(t.description),
        ].join(",")
      );
      archive.append([taskHeaders, ...taskRows].join("\n"), { name: "tasks.csv" });
    }

    // CSV: Data Collection
    if (dataCollectionItems.length > 0) {
      const dcHeaders = "System,Status,Records Found,Findings Summary,Completed At";
      const dcRows = dataCollectionItems.map((item: any) =>
        [
          escapeCSV(item.system?.name),
          escapeCSV(item.status),
          escapeCSV(String(item.recordsFound ?? "")),
          escapeCSV(item.findingsSummary),
          escapeCSV(item.completedAt ? new Date(item.completedAt).toISOString() : ""),
        ].join(",")
      );
      archive.append([dcHeaders, ...dcRows].join("\n"), { name: "data-collection.csv" });
    }

    // Data index HTML
    const dataIndexHTML = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Data Index - ${dsarCase.caseNumber}</title>
<style>body{font-family:Arial,sans-serif;margin:40px;color:#333}h1{color:#1a365d}h2{color:#1e40af;margin-top:30px}table{border-collapse:collapse;width:100%;margin:15px 0}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f8fafc}</style>
</head><body>
<h1>Data Index for ${dsarCase.caseNumber}</h1>
<p>Generated: ${new Date().toLocaleDateString()}</p>
<h2>Documents (${documents.length})</h2>
<table><tr><th>Filename</th><th>Type</th><th>Size (bytes)</th><th>Classification</th><th>Uploaded</th></tr>
${documents.map((d: any) => `<tr><td>${d.filename}</td><td>${d.contentType}</td><td>${d.size}</td><td>${d.classification}</td><td>${new Date(d.uploadedAt).toLocaleDateString()}</td></tr>`).join("")}
</table>
<h2>Data Sources Queried (${dataCollectionItems.length})</h2>
<table><tr><th>System</th><th>Status</th><th>Records Found</th><th>Summary</th></tr>
${dataCollectionItems.map((item: any) => `<tr><td>${item.system?.name ?? ""}</td><td>${item.status}</td><td>${item.recordsFound ?? "N/A"}</td><td>${item.findingsSummary ?? ""}</td></tr>`).join("")}
</table>
<h2>Audit Summary</h2>
<table><tr><th>Timestamp</th><th>Action</th><th>Details</th></tr>
${auditLogs.slice(0, 50).map((log: any) => `<tr><td>${new Date(log.createdAt).toLocaleString()}</td><td>${log.action}</td><td>${JSON.stringify(log.details ?? {})}</td></tr>`).join("")}
</table>
</body></html>`;
    archive.append(dataIndexHTML, { name: "data-index.html" });

    // Download and add each document
    const storage = getStorage();
    for (const doc of documents) {
      try {
        const fileBuffer = await storage.download(doc.storageKey);
        archive.append(fileBuffer, { name: `documents/${doc.filename}` });
      } catch {
        archive.append(
          `Failed to retrieve file: ${doc.filename} (storageKey: ${doc.storageKey})`,
          { name: `documents/${doc.filename}.error.txt` }
        );
      }
    }

    await archive.finalize();

    // Collect the stream into a buffer
    const chunks: Buffer[] = [];
    for await (const chunk of passthrough) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    }
    const buffer = Buffer.concat(chunks);

    // Log the export action
    const clientInfo = getClientInfo(request);
    await logAudit({
      tenantId: user.tenantId,
      actorUserId: user.id,
      action: "case.exported",
      entityType: "DSARCase",
      entityId: params.id,
      ip: clientInfo.ip,
      userAgent: clientInfo.userAgent,
      details: {
        caseNumber: dsarCase.caseNumber,
        documentsCount: documents.length,
        archiveSizeBytes: buffer.length,
        includesHTML: true,
        includesCSV: true,
      },
    });

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${dsarCase.caseNumber}-export.zip"`,
        "Content-Length": String(buffer.length),
      },
    });
  } catch (error) {
    return handleApiError(error);
  }
}
